version: '3.8'

services:
  app:
    build: .
    image: hospital-app-v0.1.0:latest
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase

  db:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: qwert1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
